[package]
name = "fhe-shacking-pro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tfhe = { version = "0.4.1", features = ["integer", "x86_64-unix"]}
rand = "0.8.5"
tqdm = "0.6.0"